apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: app-with-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
  spec:
    containers:
    - name: webapp
      image: gladandres/webapp
        
      ports:
        - containerPort: 5000
      env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: env-config-message
              key: special.type
      
      livenessProbe:
        httpGet:
          path: /healthz
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 5
        
      startupProbe:
        httpGet:
          path: /healthz
          port: 5000
        failureThreshold: 3
        periodSeconds: 10