apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: app-with-env
spec:
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
status:
  loadBalancer: {}